# Generated by Django 2.1.2 on 2018-10-02 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0004_aluno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.IntegerField()),
                ('disciplinaOfertada', models.IntegerField()),
            ],
        ),
    ]
