# Generated by Django 2.1.2 on 2018-10-03 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0005_matricula'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Matricula',
        ),
    ]
